# Generated by Django 5.1.2 on 2024-10-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='filtros',
            field=models.TextField(null=True, verbose_name='Filtros'),
        ),
    ]
